---
title: "Bayesian Applications"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
# Example from "Bayesian Applications of Monte Carlo" Lecture Slide on Compass
set.seed(1) # make the experiment reproducible
m <- 1000   # number of simulated values
x <- 3      # observed data

# Now simulate some random variables
theta <- rcauchy(m) # simulate m standard Cauchys
h <- pi*exp(-0.5*(x-theta)^2)  # compute h(theta)

C <- mean(h)  # estimate the normalizing constant
post.mean <- mean(theta*h)/C # estimate the posterior mean

post.mean
print("True value is 2.284967653")
```

``` {r}
# skeleton functions to be saved and edited
library(SimDesign)

#### Step 1 --- Define your conditions under study and create design data.frame

Design <- data.frame(N = c(100, 1000, 10000))

#~~~~~~~~~~~~~~~~~~~~~~~~
#### Step 2 --- Define generate, analyse, and summarise functions

# help(Generate)
Generate <- function(condition, fixed_objects = NULL){
    theta <- with(condition, rcauchy(N)) # distributed N(10, 5)
    x <- 3
    h <- pi*exp(-0.5*(x-theta)^2)
    dat <- data.frame('theta'=theta, 'h'=h)
    dat
}

# help(Analyse)
Analyse <- function(condition, dat, fixed_objects = NULL){
    ret <- mean(dat$theta*dat$h)/mean(dat$h) # mean of the sample data vector
    ret
}

# help(Summarise)
Summarise <- function(condition, results, fixed_objects = NULL){
    ret <- c(mu=mean(results), SE=sd(results)) # mean and SD summary of the sample means
    ret
}


#~~~~~~~~~~~~~~~~~~~~~~~~
#### Step 3 --- Collect results by looping over the rows in design

# run the simulation
Final <- runSimulation(design=Design, replications=1000,
                       generate=Generate, analyse=Analyse, summarise=Summarise)
Final

# reproduce exact simulation
Final_rep <- runSimulation(design=Design, replications=1000, seed=Final$SEED,
                       generate=Generate, analyse=Analyse, summarise=Summarise)
Final_rep
```

